{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggalign
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggalign_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggalign/ggalign_{{ version }}.tar.gz
  sha256: 34b1b37793e3aea0ab9cf70cee07f950dea6183b9fd3bff8bb16ae8f1d04a4d9

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-s7
    - r-cli
    - r-ggplot2 >=4.0.0
    - r-gtable
    - r-lifecycle
    - r-rlang
    - r-scales
    - r-vctrs >=0.5.0
  run:
    - r-base
    - r-s7
    - r-cli
    - r-ggplot2 >=4.0.0
    - r-gtable
    - r-lifecycle
    - r-rlang
    - r-scales
    - r-vctrs >=0.5.0

test:
  commands:
    - $R -e "library('ggalign')"           # [not win]
    - "\"%R%\" -e \"library('ggalign')\""  # [win]

about:
  home: https://github.com/Yunuuuu/ggalign, https://yunuuuu.github.io/ggalign/
  license: MIT
  summary: "A 'ggplot2' extension providing an integrative framework for composable visualization, enabling the creation of complex multi-plot layouts such as insets, circular arrangements, and multi-panel compositions. Built on the grammar of graphics, it offers tools to align, stack, and nest plots, simplifying the construction
    of richly annotated figures for high-dimensional data contexts—such as genomics, transcriptomics, and microbiome studies—by making it easy to link related plots, overlay clustering results, or highlight shared patterns."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
