{% set version = '0.0.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggalign
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggalign_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggalign/ggalign_{{ version }}.tar.gz
  sha256: a00e84beb2f7036964a6eecc17a5ba5b441969d9e8137cad79d13286c63163fa

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-data.table
    - r-ggplot2 >=3.3.0
    - r-gtable
    - r-rlang >=1.1.0
    - r-vctrs
  run:
    - r-base
    - r-cli
    - r-data.table
    - r-ggplot2 >=3.3.0
    - r-gtable
    - r-rlang >=1.1.0
    - r-vctrs

test:
  commands:
    - $R -e "library('ggalign')"           # [not win]
    - "\"%R%\" -e \"library('ggalign')\""  # [win]

about:
  home: https://github.com/Yunuuuu/ggalign, https://yunuuuu.github.io/ggalign/
  license: MIT
  summary: A 'ggplot2' extension offers various tools for organizing and arranging plots. It
    is designed to consistently align a specific axis across multiple 'ggplot' objects,
    making it especially useful for plots requiring data order manipulation. A typical
    use case includes organizing combinations like a dendrogram and a heatmap.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
